project_id = "ehccrxumpibuoehfsmms"

[functions.enforce-deadlines]
verify_jwt = false

[functions.enforce-all-deadlines]
verify_jwt = false

[functions.generate-music]
verify_jwt = false

[functions.generate-trivia]
verify_jwt = false
